[project]
name = "tongyi-deepresearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "qwen-agent[code-interpreter,gui,mcp,rag]>=0.0.31",
    "sandbox-fusion>=0.3.7",
    "transformers>=4.57.3",
]
